server:
  port: 8762
spring:
  application:
    name: zuul-server

eureka:
  instance:
    preferIpAddress: true
    hostname: ${EUREKA_HOST:localhost}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
      
      
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"